# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/HTML.gitlab-ci.yml

# Full project: https://gitlab.com/pages/plain-html
prod-s3:
  stage: deploy
  environment: production
  image: node:lts-bullseye
  variables:
    ASSET_HOST: "https://tosdr-hypothesis-prod.s3.jrbit.de/hypothesis"
    NOTEBOOK_APP_URL: "https://edit.tosdr.org/hypothesis/notebook"
    PROFILE_APP_URL: "https://edit.tosdr.org/hypothesis/user-profile"
    SIDEBAR_APP_URL: "https://edit.tosdr.org/hypothesis/app.html"
    NODE_ENV: "production"
  script:
    - make build
    - ./scripts/deploy-to-s3.js --bucket tosdr-hypothesis-prod
  rules:
  - if: $CI_COMMIT_TAG


# Full project: https://gitlab.com/pages/plain-html
staging-s3:
  stage: deploy
  environment: staging
  image: node:lts-bullseye
  variables:
    ASSET_HOST: "https://tosdr-hypothesis-staging.s3.jrbit.de/hypothesis"
    NOTEBOOK_APP_URL: "https://edit.staging.tosdr.org/hypothesis/notebook"
    PROFILE_APP_URL: "https://edit.staging.tosdr.org/hypothesis/user-profile"
    SIDEBAR_APP_URL: "https://edit.staging.tosdr.org/hypothesis/app.html"
    NODE_ENV: "production"
  script:
    - make build && ./scripts/deploy-to-s3.js --bucket tosdr-hypothesis-staging
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
